<a href="https://colab.research.google.com/github/YooraHi/Project/blob/main/project01(re).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.데이터 가져오기
from sklearn.datasets import load_diabetes

diabetes=load_diabetes()

df_x=diabetes.data
df_y=diabetes.target

#2.모델에 입력할 데이터 준비하기 
print(df_x.shape)
print(df_y.shape)

(442, 10)
(442,)

In [ ]:
#1-1. diabetes.data 10개 특성 확인 
for i,feature_name in enumerate(diabetes.feature_names):
  print(f'feature {i+1} : {feature_name}')

#2.pandas check
import pandas as pd
import numpy as np

#data=diabetes.data
#colums=diabetes.feature_names
df.head()
df = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)
df['target']= diabetes.target
df.corr()

feature 1 : age
feature 2 : sex
feature 3 : bmi
feature 4 : bp
feature 5 : s1
feature 6 : s2
feature 7 : s3
feature 8 : s4
feature 9 : s5
feature 10 : s6

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
age,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,0.187889
sex,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.043062
bmi,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.586450
bp,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.441482
s1,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.212022
s2,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.174054
s3,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.394789
s4,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.430453
s5,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.565883
s6,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.382483
target,0.187889,0.043062,0.586450,0.441482,0.212022,0.174054,-0.394789,0.430453,0.565883,0.382483,1.000000

In [ ]:
#numpy로 변환 
df_x=np.array(df_x)
df_y=np.array(df_y)

In [ ]:
#x는 train 데이터와 y는 test 데이터로 분리하기

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3) #train과 test를 7:3의 비율로 나누었습니다.
len(x_train), len(y_train), len(y_test) #실제로 잘 나누어졌는지 확인

print("train sh",x_train.shape,x_test.shape)
print("test sh ",y_train.shape,y_test.shape)

train sh (309, 10) (133, 10)
test sh  (309,) (133,)

In [ ]:
#model 준비 

#입력 데이터 개수에 맞는 가중치 W와 b를 준비해주세요.- colums = features 1~10, data fram = data 1

W = np.random.rand(x_train.shape[1])
b = np.random.rand(1)


#모델 함수를 구현해주세요.

def model(x,w,b):
    pred = 0
    for i in range(w.shape[0]):
        pred += x[:,i]*w[i]
    pred += b
    return pred

In [ ]:
#손실함수 구현 -MSE로 구현 
def MSE(x, b):
    return ((x - b)**2).mean()

In [3]:
#gradient 함수 구현 (기울기)

def gradient(x, w, b, y):
    N = len(y)
    y_pred = model(x, w, b)

In [4]:
#8.하이퍼 파라미터인 학습률 설정하기
Ir = 0.5

In [6]:
#9.모델 학습하기 

losses_save = []
iter_n = 5000

# def remake_input(x):
#     new_input = np.delete(x,1,axis=1)*100
#     return new_input
    


# w = np.random.rand(x_train_remake.shape[1])
# b = np.random.rand(1)

for i in range(1, iter_n):
    dw, db = gradient(x_train, w, b, y_train)
    w -= lr * dw
    b -= lr * db
    
    y_pred = model(x_train,w,b)
    L = MSE(y_pred,y_train)
    losses_save.append(L)
    if i % 100 == 0:
        print('Iteration %d : Loss %0.4f' % (i, L))
print(W,b)

NameError: ignored